- name: build galene
  ansible.builtin.command:
    cmd: go build -ldflags='-s -w'
    chdir: "{{ galene.folder }}/server"
  environment:
    CGO_ENABLED: 0
  become_user: galene

- name: restart galene
  ansible.builtin.systemd:
    name: galene
    state: restarted
    enabled: yes